name: Release

on:
  push:
    branches:
      - "master"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update the Package Lists
        run: sudo apt update

      - name: Install LaTeX
        run: sudo apt install texlive-full

      - name: Compile the Project
        run: make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: main.pdf

      - name: Setup Tmate Session
        if: failure()
        uses: mxschmitt/action-tmate/detached@v3

  release:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: main.pdf
          path: main.pdf

      - name: Get Current Timestamp
        run: echo "TIMESTAMP=$(date -Is)" >> $GITHUB_ENV

      - name: Release the Document
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: phd_${{env.TIMESTAMP}}.pdf
          file: main.pdf

      - name: Setup Tmate Session
        if: failure()
        uses: mxschmitt/action-tmate/detached@v3
