name: Release

on:
  push:
    branches:
      - "master"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Compile LaTeX Documents
        uses: xu-cheng/texlive-action@v3
        with:
          run: ONLINE=1 arara main cover

      - name: Obtain the Short SHA
        run: echo "SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Release the Document
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: phd_${{env.SHA_SHORT}}.pdf
          body: "Automated release for commit ${{github.sha}}."
          file: main.pdf
          release_name: "Release: Commit ${{env.SHA_SHORT}}"
          tag: release-${{env.SHA_SHORT}}

      - name: Release the Cover
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: cover_${{env.SHA_SHORT}}.pdf
          file: cover.pdf
          tag: release-${{env.SHA_SHORT}}

      - name: Setup Tmate Session
        if: failure()
        uses: mxschmitt/action-tmate/detached@v3
