name: Release

on:
  push:
    branches:
      - "master"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          latexmk_use_lualatex: true

      - name: Release the Document
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: phd_${{github.sha}}.pdf
          body: "Automated release for commit ${{github.sha}}."
          file: main.pdf
          overwrite: true
          release_name: "Release: Commit ${{github.sha}}"
          tag: release-${{github.run_number}}-${{github.sha}}

      - name: Setup Tmate Session
        if: failure()
        uses: mxschmitt/action-tmate/detached@v3
